//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auto()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int ID_Auto { get; set; }
        public Nullable<int> Marca_ID { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public Nullable<int> Cilindros { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Tipo_ID { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual TipoAuto TipoAuto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
