//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int ID_Venta { get; set; }
        public Nullable<int> Auto_ID { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<int> Vendedor_ID { get; set; }
        public string Estatus { get; set; }
        public Nullable<int> Agencia_ID { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Auto Auto { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
