//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaAutosMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Ventas_Detalles
    {
        public int ID_Venta { get; set; }
        public int ID_Auto { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public Nullable<int> Cilindros { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Tipo_Auto { get; set; }
        public int ID_Cliente { get; set; }
        public string Cliente { get; set; }
        public string RFC { get; set; }
        public string Email_Cliente { get; set; }
        public string Tel_Cliente { get; set; }
        public int ID_Vendedor { get; set; }
        public string Vendedor { get; set; }
        public string Matricula_Vendedor { get; set; }
        public string Email_Vendedor { get; set; }
        public string Tel_Vendedor { get; set; }
        public int ID_Agencia { get; set; }
        public string Agencia { get; set; }
        public string Tel_Agencia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total_Precio { get; set; }
    }
}
